export const FETCH_SYSTEM_CINEMA_REQUEST = "FETCH_SYSTEM_CINEMA_REQUEST";
export const FETCH_SYSTEM_CINEMA_SUCCESS = "FETCH_SYSTEM_CINEMA_SUCCESS";
export const FETCH_SYSTEM_CINEMA_FAILED = "FETCH_SYSTEM_CINEMA_FAILED";

export const FETCH_SYSTEM_CINEMA_AGENTS_REQUEST = "FETCH_SYSTEM_CINEMA_AGENTS_REQUEST";
export const FETCH_SYSTEM_CINEMA_AGENTS_SUCCESS = "FETCH_SYSTEM_CINEMA_AGENTS_SUCCESS";
export const FETCH_SYSTEM_CINEMA_AGENTS_FAILED = "FETCH_SYSTEM_CINEMA_AGENTS_FAILED";